# Generated by Django 2.1 on 2018-09-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='weixin_user',
            name='openid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
