# Generated by Django 2.1 on 2018-09-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20180918_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_info',
            name='account_info',
        ),
        migrations.AddField(
            model_name='class_info',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weixin.Order_info'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
