# Generated by Django 2.1 on 2018-09-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20180918_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_info',
            name='account_info',
        ),
    ]
